import groovy.json.JsonSlurper

pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
}

rootProject.name = 'dimension-bridge'
include 'velocity'

def targets = new JsonSlurper().parse(file('gradle/fabric-targets.json'))
targets.each { target ->
    String projectName = "fabric-${target.minecraft}"
    include projectName
    project(":${projectName}").projectDir = file("fabric-versions/${target.minecraft}")
}
